// Generated by `aip gen ts` from the AIP contract aip-protocol/0.1 (core aip-core/0.11). Do not edit.
/* eslint-disable */

export type ApprovalDecision = 'APPROVE' | 'REJECT';
export type ApprovalStatus = 'NONE' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'EXPIRED';
export type JobStatus = 'QUEUED' | 'RUNNING' | 'DONE' | 'FAILED';
export type TaskStatus = 'OPEN' | 'DONE' | 'ARCHIVED';
export type WorkspaceRole = 'MEMBER' | 'ADMIN';

export type TaskPair = { first: string; second: string };

export type ArchiveDoneStatusInput = { job: string };
export type ArchiveDoneStatusOutput = { createdAt: string; done: number; error: string | null; file: string | null; finishedAt: string | null; startedAt: string | null; status: JobStatus; total: number | null };
export type ArchiveDoneStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND' };

export type GetProjectInput = { project: string };
export type GetProjectOutput = { id: string; title: string; workspace: { id: string; name: string } | null };
export type GetProjectError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' };

export type MyTasksInput = { workspace: string };
export type MyTasksOutput = Array<{ id: string; project: { id: string; title: string } | null; title: string }>;
export type MyTasksError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' };

export type MyWorkspacesInput = {  };
export type MyWorkspacesOutput = Array<{ id: string; role: WorkspaceRole; workspace: { id: string; name: string } | null }>;
export type MyWorkspacesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type OpenTaskCountInput = { workspace: string };
export type OpenTaskCountOutput = { open: number };
export type OpenTaskCountError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' };

export type ProjectEndpointsInput = { project: string };
export type ProjectEndpointsOutput = Array<{ id: string; url: string }>;
export type ProjectEndpointsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' };

export type ProjectTasksInput = { project: string };
export type ProjectTasksOutput = Array<{ id: string; status: TaskStatus; title: string }>;
export type ProjectTasksError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' };

export type SearchProjectsInput = { workspace: string; q: string };
export type SearchProjectsOutput = Array<{ id: string; rank: string; title: string }>;
export type SearchProjectsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' };

export type SearchTasksInput = { workspace: string; q: string };
export type SearchTasksOutput = Array<{ id: string; rank: string; status: TaskStatus; title: string }>;
export type SearchTasksError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' };

export type TaskCommentsInput = { task: string };
export type TaskCommentsOutput = Array<{ author: { email: string } | null; body: string; id: string }>;
export type TaskCommentsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' };

export type TaskSignoffStatusInput = { task: string };
export type TaskSignoffStatusOutput = { approvals: number; canVote: boolean; decidedAt: string | null; expiresAt: string | null; requestedAt: string | null; requestedBy: string | null; required: number; status: ApprovalStatus; votes: Array<{ at: string; comment: string | null; decision: ApprovalDecision; voter: string }> };
export type TaskSignoffStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' };

export type WelcomeDefaultsStatusInput = { job: string };
export type WelcomeDefaultsStatusOutput = { createdAt: string; done: number; error: string | null; file: string | null; finishedAt: string | null; startedAt: string | null; status: JobStatus; total: number | null };
export type WelcomeDefaultsStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND' };

export type AddCommentInput = { task: string; body: string };
export type AddCommentOutput = { body: string; id: string };
export type AddCommentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type AddEndpointInput = { project: string; url: string };
export type AddEndpointOutput = { id: string; secret: string; url: string };
export type AddEndpointError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ENDPOINT_EXISTS' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type AddMemberInput = { workspace: string; member: string };
export type AddMemberOutput = null;
export type AddMemberError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'MEMBER_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' };

export type AddReviewerInput = { project: string; member: string };
export type AddReviewerOutput = null;
export type AddReviewerError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REVIEWER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'MEMBER_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type ApproveTaskSignoffInput = { task: string; comment?: string | null };
export type ApproveTaskSignoffOutput = null;
export type ApproveTaskSignoffError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'NOT_AN_APPROVER' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_VOTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type ArchiveDoneInput = { workspace: string };
export type ArchiveDoneOutput = { job: string; status: JobStatus };
export type ArchiveDoneError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' };

export type CancelTaskSignoffInput = { task: string };
export type CancelTaskSignoffOutput = null;
export type CancelTaskSignoffError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'ONLY_REQUESTER_CAN_CANCEL' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' };

export type CloneToMyDefaultInput = { task: string };
export type CloneToMyDefaultOutput = { id: string };
export type CloneToMyDefaultError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NO_DEFAULT_PROJECT' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type CompleteTaskInput = { task: string };
export type CompleteTaskOutput = null;
export type CompleteTaskError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type CreateProjectInput = { workspace: string; title: string };
export type CreateProjectOutput = { id: string; title: string };
export type CreateProjectError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type CreateTaskInput = { project: string; title: string; notes?: string | null; parent?: string | null; assignee?: string | null };
export type CreateTaskOutput = { id: string; title: string };
export type CreateTaskError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'MEMBER_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type CreateWorkspaceInput = { name: string };
export type CreateWorkspaceOutput = { id: string; name: string };
export type CreateWorkspaceError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_MEMBER' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' };

export type MoveTaskInput = { task: string; project: string };
export type MoveTaskOutput = null;
export type MoveTaskError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type MoveToMyDefaultInput = { task: string };
export type MoveToMyDefaultOutput = null;
export type MoveToMyDefaultError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NO_DEFAULT_PROJECT' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type PinParentInput = { task: string };
export type PinParentOutput = null;
export type PinParentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NOTHING_PINNED' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type RejectTaskSignoffInput = { task: string; reason?: string | null };
export type RejectTaskSignoffOutput = null;
export type RejectTaskSignoffError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'NOT_AN_APPROVER' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_VOTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type RenameProjectInput = { project: string; title: string };
export type RenameProjectOutput = null;
export type RenameProjectError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type RequestTaskSignoffInput = { task: string };
export type RequestTaskSignoffOutput = null;
export type RequestTaskSignoffError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'APPROVAL_ALREADY_PENDING' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'TASK_NOT_FOUND' };

export type WelcomeDefaultsInput = {  };
export type WelcomeDefaultsOutput = { job: string; status: JobStatus };
export type WelcomeDefaultsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' };

export type LiveProjectTasksInput = { project: string };
export type LiveProjectTasksOutput = Array<{ id: string; status: TaskStatus; title: string }>;
export type LiveProjectTasksError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PROJECT_NOT_FOUND' }
  | { code: 'AIP.SUBSCRIPTION.LIMIT' }
  | { code: 'AIP.SUBSCRIPTION.TOO_LARGE' };

export type LiveWorkspaceTasksInput = { workspace: string };
export type LiveWorkspaceTasksOutput = Array<{ id: string; status: TaskStatus; title: string }>;
export type LiveWorkspaceTasksError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'WORKSPACE_NOT_FOUND' }
  | { code: 'AIP.SUBSCRIPTION.LIMIT' }
  | { code: 'AIP.SUBSCRIPTION.TOO_LARGE' };

export interface AipErrorBody {
  code: string;
  intent: string;
  reason?: string;
  path?: string;
  message: string;
  retryable: boolean;
}

/** Thrown for every failed call; `body` is narrowed per intent by the generated error unions. */
export class AipError<E = { code: string }> extends Error {
  readonly body: AipErrorBody & E;
  readonly status: number;
  constructor(status: number, body: AipErrorBody & E) {
    super(`${body.code}${body.reason ? ` (${body.reason})` : ''}: ${body.message}`);
    this.status = status;
    this.body = body;
  }
}

export interface ClientOptions {
  baseUrl: string;
  /** Bearer token, or a function returning one (for refresh). */
  token?: string | (() => string | undefined | Promise<string | undefined>);
  fetch?: typeof fetch;
}

export interface PageRequest {
  cursor?: string | null;
  page?: number;
}

export interface Page {
  next_cursor?: string | null;
  has_more: boolean;
}

export interface Result<O> {
  data: O;
  page?: Page;
  items?: Array<{ index: number; ok: boolean; error?: AipErrorBody }>;
}

/** Replaces Blob values with part names and collects the files for multipart upload. */
function extractFiles(value: unknown, files: Map<string, Blob>): unknown {
  if (typeof Blob !== 'undefined' && value instanceof Blob) {
    const name = `file${files.size}`;
    files.set(name, value);
    return name;
  }
  if (Array.isArray(value)) return value.map((v) => extractFiles(v, files));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, extractFiles(v, files)]));
  }
  return value;
}

function makeCall(opts: ClientOptions) {
  const f = opts.fetch ?? fetch;
  return async function call<O, E>(intent: string, input: unknown, idempotencyKey?: string): Promise<Result<O>> {
    const headers: Record<string, string> = {};
    const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
    if (token) headers['authorization'] = `Bearer ${token}`;
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const files = new Map<string, Blob>();
    const payload = extractFiles(input, files);
    let body: BodyInit;
    if (files.size > 0) {
      const form = new FormData();
      form.append('input', JSON.stringify(payload));
      for (const [name, blob] of files) form.append(name, blob, (blob as File).name ?? name);
      body = form;
    } else {
      headers['content-type'] = 'application/json';
      body = JSON.stringify(payload);
    }
    const res = await f(`${opts.baseUrl}/aip/${intent}`, { method: 'POST', headers, body });
    const json = (await res.json()) as { data?: O; page?: Page; items?: Result<O>['items']; error?: AipErrorBody };
    if (!res.ok || json.error) throw new AipError<E>(res.status, json.error as AipErrorBody & E);
    return { data: json.data as O, page: json.page, items: json.items };
  };
}

export interface SubscribeClientOptions extends ClientOptions {
  /** The WebSocket constructor; defaults to the global one (browsers, Node 22+). */
  webSocket?: typeof WebSocket;
}

export interface Subscription {
  /** Ends the subscription and closes its connection. Safe to call twice. */
  close(): void;
}

/** What the server says when it ends a subscription, or the connection drops (`AIP.UNAVAILABLE`). */
export type SubscriptionFailure<E> = AipErrorBody & E;

function makeSubscribe<M extends Record<string, { input: unknown; output: unknown; error: unknown }>>(opts: SubscribeClientOptions) {
  return function subscribe<N extends keyof M & string>(
    name: N,
    input: M[N]['input'],
    onRows: (rows: M[N]['output'], kind: 'snapshot' | 'changed') => void,
    onError?: (error: SubscriptionFailure<M[N]['error']>) => void,
  ): Subscription {
    const WS = opts.webSocket ?? WebSocket;
    const id = Math.random().toString(36).slice(2);
    let done = false;
    const ws = new WS(`${opts.baseUrl.replace(/^http/, 'ws')}/aip/subscribe`);
    const fail = (body: AipErrorBody & { id?: string }) => {
      if (done) return;
      done = true;
      ws.close();
      onError?.(body as SubscriptionFailure<M[N]['error']>);
    };
    ws.onopen = async () => {
      // the token goes in the first message, not in the URL: URLs end up in logs and browsers cannot set headers on a WebSocket
      const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
      ws.send(JSON.stringify({ type: 'auth', ...(token ? { token } : {}) }));
      ws.send(JSON.stringify({ type: 'subscribe', id, name, input }));
    };
    ws.onmessage = (ev) => {
      const msg = JSON.parse(String(ev.data)) as { type: string; id?: string; rows?: M[N]['output'] } & AipErrorBody;
      if (msg.id !== undefined && msg.id !== id) return;
      if (msg.type === 'snapshot' || msg.type === 'changed') {
        if (!done) onRows(msg.rows as M[N]['output'], msg.type);
      } else if (msg.type === 'error') {
        fail(msg);
      }
    };
    ws.onerror = () => fail({ code: 'AIP.UNAVAILABLE', intent: name, message: 'the connection failed', retryable: true });
    ws.onclose = () => fail({ code: 'AIP.UNAVAILABLE', intent: name, message: 'the connection was closed', retryable: true });
    return {
      close() {
        if (done) return;
        done = true;
        ws.close();
      },
    };
  };
}

export type Subscriptions = {
  LiveProjectTasks: { input: LiveProjectTasksInput; output: LiveProjectTasksOutput; error: LiveProjectTasksError };
  LiveWorkspaceTasks: { input: LiveWorkspaceTasksInput; output: LiveWorkspaceTasksOutput; error: LiveWorkspaceTasksError };
};

export function createClient(opts: SubscribeClientOptions) {
  const call = makeCall(opts);
  return {
    queries: {
      ArchiveDoneStatus: (input: ArchiveDoneStatusInput) => call<ArchiveDoneStatusOutput, ArchiveDoneStatusError>('ArchiveDoneStatus', input),
      GetProject: (input: GetProjectInput) => call<GetProjectOutput, GetProjectError>('GetProject', input),
      MyTasks: (input: MyTasksInput, page?: PageRequest) => call<MyTasksOutput, MyTasksError>('MyTasks', { ...input, ...(page ?? {}) }),
      MyWorkspaces: (input: MyWorkspacesInput, page?: PageRequest) => call<MyWorkspacesOutput, MyWorkspacesError>('MyWorkspaces', { ...input, ...(page ?? {}) }),
      OpenTaskCount: (input: OpenTaskCountInput) => call<OpenTaskCountOutput, OpenTaskCountError>('OpenTaskCount', input),
      ProjectEndpoints: (input: ProjectEndpointsInput, page?: PageRequest) => call<ProjectEndpointsOutput, ProjectEndpointsError>('ProjectEndpoints', { ...input, ...(page ?? {}) }),
      ProjectTasks: (input: ProjectTasksInput, page?: PageRequest) => call<ProjectTasksOutput, ProjectTasksError>('ProjectTasks', { ...input, ...(page ?? {}) }),
      SearchProjects: (input: SearchProjectsInput, page?: PageRequest) => call<SearchProjectsOutput, SearchProjectsError>('SearchProjects', { ...input, ...(page ?? {}) }),
      SearchTasks: (input: SearchTasksInput, page?: PageRequest) => call<SearchTasksOutput, SearchTasksError>('SearchTasks', { ...input, ...(page ?? {}) }),
      TaskComments: (input: TaskCommentsInput, page?: PageRequest) => call<TaskCommentsOutput, TaskCommentsError>('TaskComments', { ...input, ...(page ?? {}) }),
      TaskSignoffStatus: (input: TaskSignoffStatusInput) => call<TaskSignoffStatusOutput, TaskSignoffStatusError>('TaskSignoffStatus', input),
      WelcomeDefaultsStatus: (input: WelcomeDefaultsStatusInput) => call<WelcomeDefaultsStatusOutput, WelcomeDefaultsStatusError>('WelcomeDefaultsStatus', input),
    },
    commands: {
      AddComment: (input: AddCommentInput, o: { idempotencyKey: string }) => call<AddCommentOutput, AddCommentError>('AddComment', input, o.idempotencyKey),
      AddEndpoint: (input: AddEndpointInput) => call<AddEndpointOutput, AddEndpointError>('AddEndpoint', input),
      AddMember: (input: AddMemberInput) => call<AddMemberOutput, AddMemberError>('AddMember', input),
      AddReviewer: (input: AddReviewerInput) => call<AddReviewerOutput, AddReviewerError>('AddReviewer', input),
      ApproveTaskSignoff: (input: ApproveTaskSignoffInput) => call<ApproveTaskSignoffOutput, ApproveTaskSignoffError>('ApproveTaskSignoff', input),
      ArchiveDone: (input: ArchiveDoneInput) => call<ArchiveDoneOutput, ArchiveDoneError>('ArchiveDone', input),
      CancelTaskSignoff: (input: CancelTaskSignoffInput) => call<CancelTaskSignoffOutput, CancelTaskSignoffError>('CancelTaskSignoff', input),
      CloneToMyDefault: (input: CloneToMyDefaultInput, o: { idempotencyKey: string }) => call<CloneToMyDefaultOutput, CloneToMyDefaultError>('CloneToMyDefault', input, o.idempotencyKey),
      CompleteTask: (input: CompleteTaskInput) => call<CompleteTaskOutput, CompleteTaskError>('CompleteTask', input),
      CreateProject: (input: CreateProjectInput, o: { idempotencyKey: string }) => call<CreateProjectOutput, CreateProjectError>('CreateProject', input, o.idempotencyKey),
      CreateTask: (input: CreateTaskInput, o: { idempotencyKey: string }) => call<CreateTaskOutput, CreateTaskError>('CreateTask', input, o.idempotencyKey),
      CreateWorkspace: (input: CreateWorkspaceInput, o: { idempotencyKey: string }) => call<CreateWorkspaceOutput, CreateWorkspaceError>('CreateWorkspace', input, o.idempotencyKey),
      MoveTask: (input: MoveTaskInput) => call<MoveTaskOutput, MoveTaskError>('MoveTask', input),
      MoveToMyDefault: (input: MoveToMyDefaultInput) => call<MoveToMyDefaultOutput, MoveToMyDefaultError>('MoveToMyDefault', input),
      PinParent: (input: PinParentInput) => call<PinParentOutput, PinParentError>('PinParent', input),
      RejectTaskSignoff: (input: RejectTaskSignoffInput) => call<RejectTaskSignoffOutput, RejectTaskSignoffError>('RejectTaskSignoff', input),
      RenameProject: (input: RenameProjectInput) => call<RenameProjectOutput, RenameProjectError>('RenameProject', input),
      RequestTaskSignoff: (input: RequestTaskSignoffInput) => call<RequestTaskSignoffOutput, RequestTaskSignoffError>('RequestTaskSignoff', input),
      WelcomeDefaults: (input: WelcomeDefaultsInput) => call<WelcomeDefaultsOutput, WelcomeDefaultsError>('WelcomeDefaults', input),
    },
    subscribe: makeSubscribe<Subscriptions>(opts),
  };
}
