// Generated by `aip gen ts` from the AIP contract aip-protocol/0.1 (core aip-core/0.11). Do not edit.
/* eslint-disable */

export type CustomerRole = 'USER' | 'STAFF';
export type OrderStatus = 'PENDING' | 'PAID' | 'CANCELLED' | 'REFUNDED';

export type PaymentMeta = { orderId: string };
export type StripePaymentIntent = { id: string; amount: number; currency: string; metadata: PaymentMeta };

export type CatalogInput = {  };
export type CatalogOutput = Array<{ featured: boolean; id: string; name: string; price: number; stock: number; version: number }>;
export type CatalogError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type MyOrderInput = { order: string };
export type MyOrderOutput = { amount: number; id: string; paidAt: string | null; paymentRef: string | null; status: OrderStatus };
export type MyOrderError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ORDER_NOT_FOUND' };

export type PlaceOrderInput = { product: string; quantity: number };
export type PlaceOrderOutput = { amount: number; id: string; status: OrderStatus };
export type PlaceOrderError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'OUT_OF_STOCK' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PRODUCT_NOT_FOUND' };

export type RestockInput = { product: string; quantity: number };
export type RestockOutput = null;
export type RestockError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'OUT_OF_STOCK' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PRODUCT_NOT_FOUND' };

export type UpdateProductInput = { product: string; name: string; price: number; productVersion: number };
export type UpdateProductOutput = null;
export type UpdateProductError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.STALE_VERSION'; reason: 'PRODUCT_VERSION_STALE' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'OUT_OF_STOCK' }
  | { code: 'AIP.NOT_FOUND'; reason: 'PRODUCT_NOT_FOUND' };

export interface AipErrorBody {
  code: string;
  intent: string;
  reason?: string;
  path?: string;
  message: string;
  retryable: boolean;
}

/** Thrown for every failed call; `body` is narrowed per intent by the generated error unions. */
export class AipError<E = { code: string }> extends Error {
  readonly body: AipErrorBody & E;
  readonly status: number;
  constructor(status: number, body: AipErrorBody & E) {
    super(`${body.code}${body.reason ? ` (${body.reason})` : ''}: ${body.message}`);
    this.status = status;
    this.body = body;
  }
}

export interface ClientOptions {
  baseUrl: string;
  /** Bearer token, or a function returning one (for refresh). */
  token?: string | (() => string | undefined | Promise<string | undefined>);
  fetch?: typeof fetch;
}

export interface PageRequest {
  cursor?: string | null;
  page?: number;
}

export interface Page {
  next_cursor?: string | null;
  has_more: boolean;
}

export interface Result<O> {
  data: O;
  page?: Page;
  items?: Array<{ index: number; ok: boolean; error?: AipErrorBody }>;
}

/** Replaces Blob values with part names and collects the files for multipart upload. */
function extractFiles(value: unknown, files: Map<string, Blob>): unknown {
  if (typeof Blob !== 'undefined' && value instanceof Blob) {
    const name = `file${files.size}`;
    files.set(name, value);
    return name;
  }
  if (Array.isArray(value)) return value.map((v) => extractFiles(v, files));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, extractFiles(v, files)]));
  }
  return value;
}

function makeCall(opts: ClientOptions) {
  const f = opts.fetch ?? fetch;
  return async function call<O, E>(intent: string, input: unknown, idempotencyKey?: string): Promise<Result<O>> {
    const headers: Record<string, string> = {};
    const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
    if (token) headers['authorization'] = `Bearer ${token}`;
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const files = new Map<string, Blob>();
    const payload = extractFiles(input, files);
    let body: BodyInit;
    if (files.size > 0) {
      const form = new FormData();
      form.append('input', JSON.stringify(payload));
      for (const [name, blob] of files) form.append(name, blob, (blob as File).name ?? name);
      body = form;
    } else {
      headers['content-type'] = 'application/json';
      body = JSON.stringify(payload);
    }
    const res = await f(`${opts.baseUrl}/aip/${intent}`, { method: 'POST', headers, body });
    const json = (await res.json()) as { data?: O; page?: Page; items?: Result<O>['items']; error?: AipErrorBody };
    if (!res.ok || json.error) throw new AipError<E>(res.status, json.error as AipErrorBody & E);
    return { data: json.data as O, page: json.page, items: json.items };
  };
}

export function createClient(opts: ClientOptions) {
  const call = makeCall(opts);
  return {
    queries: {
      Catalog: (input: CatalogInput, page?: PageRequest) => call<CatalogOutput, CatalogError>('Catalog', { ...input, ...(page ?? {}) }),
      MyOrder: (input: MyOrderInput) => call<MyOrderOutput, MyOrderError>('MyOrder', input),
    },
    commands: {
      PlaceOrder: (input: PlaceOrderInput, o: { idempotencyKey: string }) => call<PlaceOrderOutput, PlaceOrderError>('PlaceOrder', input, o.idempotencyKey),
      Restock: (input: RestockInput) => call<RestockOutput, RestockError>('Restock', input),
      UpdateProduct: (input: UpdateProductInput) => call<UpdateProductOutput, UpdateProductError>('UpdateProduct', input),
    },
  };
}
