// Generated by `aip gen ts` from the AIP contract aip-protocol/0.1 (core aip-core/0.11). Do not edit.
/* eslint-disable */

export type AccessType = 'PUBLIC' | 'CLUB_ONLY';
export type Affiliation = 'INTERNAL' | 'UNION';
export type ApplyStatus = 'PENDING' | 'INTERVIEW' | 'APPROVED' | 'REFUSED';
export type ApprovalDecision = 'APPROVE' | 'REJECT';
export type ApprovalStatus = 'NONE' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'EXPIRED';
export type ClubRole = 'GENERAL' | 'MANAGER' | 'ADMIN';
export type Field = 'CULTURE' | 'VOLUNTEER' | 'ACADEMIC' | 'STARTUP' | 'CAREER' | 'SPORTS' | 'SOCIAL' | 'ETC';
export type JobStatus = 'QUEUED' | 'RUNNING' | 'DONE' | 'FAILED';
export type MemberRole = 'USER' | 'SUPER_ADMIN';
export type MemberStatus = 'ACTIVE' | 'ENDED';
export type QuestionKind = 'TEXT' | 'CHOICE' | 'FILE';
export type RecruitmentSort = 'LATEST' | 'VIEWS' | 'SCRAPS' | 'OLDEST' | 'DEADLINE';
export type RecruitmentStatus = 'PENDING_APPROVAL' | 'PUBLISHED' | 'CLOSED';
export type Region = 'ANY' | 'CAPITAL' | 'CHUNGCHEONG' | 'GYEONGNAM' | 'GYEONGBUK' | 'JEOLLA' | 'GANGWON' | 'JEONBUK' | 'JEJU' | 'OVERSEAS';
export type ReportStatus = 'OPEN' | 'RESOLVED' | 'DISMISSED';
export type ReportTarget = 'CLUB_REVIEW' | 'PASS_REVIEW' | 'QUESTION' | 'COMMENT';
export type Settlement = 'OPEN' | 'SETTLED' | 'DISPUTED';
export type Target = 'UNDERGRADUATE' | 'GRADUATE' | 'WORKER';

export type ClubInput = { name: string; intro: string; affiliation: Affiliation; field: Field; region: Region; target: Target };
export type Question = { key: string; label: string; kind: QuestionKind; required: boolean; maxLength?: number | null; choices: Array<string> };
export type RecruitmentFilter = { fields: Array<Field>; regions: Array<Region>; targets: Array<Target>; affiliations: Array<Affiliation> };
export type RecruitmentInput = { title: string; body: string; period: { start: string; end: string }; field: Field; region: Region; target: Target; externalUrl?: string | null };

export type ActivityDetailInput = { activity: string };
export type ActivityDetailOutput = { access: AccessType; author: { nickname: string } | null; body: string; comments: Array<{ author: { nickname: string } | null; body: string; createdAt: string; id: string; likeCount: number; parent: string | null }>; createdAt: string; id: string; images: Array<{ image: string }>; likeCount: number; liked: boolean };
export type ActivityDetailError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_ACTIVITY_NOT_FOUND' };

export type ApplyDetailInput = { apply: string };
export type ApplyDetailOutput = { answers: unknown; createdAt: string; file: string | null; form: { id: string; version: number }; id: string; member: { nickname: string } | null; portfolioUrl: string | null; recruitment: { id: string; title: string } | null; status: ApplyStatus };
export type ApplyDetailError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_NOT_FOUND' };

export type ClubActiveRecruitmentInput = { club: string };
export type ClubActiveRecruitmentOutput = Array<{ id: string; period: { start: string; end: string }; title: string }>;
export type ClubActiveRecruitmentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ClubActivitiesInput = { club: string };
export type ClubActivitiesOutput = Array<{ access: AccessType; author: { nickname: string } | null; body: string; commentCount: number; createdAt: string; id: string; images: Array<{ image: string }>; likeCount: number; liked: boolean }>;
export type ClubActivitiesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ClubBalanceInput = { club: string };
export type ClubBalanceOutput = { balance: string };
export type ClubBalanceError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ClubDetailInput = { club: string };
export type ClubDetailOutput = { affiliation: Affiliation; banner: string | null; bookmarkCount: number; field: Field; id: string; intro: string; isBookmarked: boolean; myMembership: { id: string; name: string; role: ClubRole; status: MemberStatus } | null; name: string; profile: string | null; region: Region; school: { name: string } | null; target: Target; views: number };
export type ClubDetailError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ClubListInput = { filter: RecruitmentFilter; sort?: RecruitmentSort | null };
export type ClubListOutput = Array<{ affiliation: Affiliation; bookmarkCount: number; field: Field; id: string; name: string; profile: string | null; region: Region; target: Target }>;
export type ClubListError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type ClubMembersInput = { club: string; status?: MemberStatus | null; q?: string | null };
export type ClubMembersOutput = Array<{ id: string; member: { nickname: string; profile: string | null } | null; name: string; role: ClubRole; status: MemberStatus }>;
export type ClubMembersError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ClubNoticesInput = { club: string };
export type ClubNoticesOutput = Array<{ author: { nickname: string } | null; createdAt: string; fixed: boolean; id: string; title: string }>;
export type ClubNoticesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ClubQuestionsInput = { club: string };
export type ClubQuestionsOutput = Array<{ answer: string | null; author: { nickname: string } | null; body: string; createdAt: string; id: string; title: string }>;
export type ClubQuestionsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type EventAttendeesInput = { event: string };
export type EventAttendeesOutput = Array<{ createdAt: string; id: string; member: { nickname: string } | null }>;
export type EventAttendeesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' };

export type ExportApplicantsStatusInput = { job: string };
export type ExportApplicantsStatusOutput = { createdAt: string; done: number; error: string | null; file: string | null; finishedAt: string | null; startedAt: string | null; status: JobStatus; total: number | null };
export type ExportApplicantsStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND' };

export type FinancialLedgerInput = { club: string };
export type FinancialLedgerOutput = Array<{ amount: string; at: string; balance: string; id: string; memo: string }>;
export type FinancialLedgerError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type FinancialSettlementStatusInput = { financialRecord: string };
export type FinancialSettlementStatusOutput = { approvals: number; canVote: boolean; decidedAt: string | null; expiresAt: string | null; requestedAt: string | null; requestedBy: string | null; required: number; status: ApprovalStatus; votes: Array<{ at: string; comment: string | null; decision: ApprovalDecision; voter: string }> };
export type FinancialSettlementStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' };

export type GetClubEventInput = { target: string };
export type GetClubEventOutput = { at: string; club: string; id: string; place: string; title: string };
export type GetClubEventError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' };

export type GetClubFaqInput = { target: string };
export type GetClubFaqOutput = { answer: string; club: string; id: string; question: string; rank: string };
export type GetClubFaqError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_FAQ_NOT_FOUND' };

export type ListClubEventInput = { club: string };
export type ListClubEventOutput = Array<{ at: string; club: string; id: string; place: string; title: string }>;
export type ListClubEventError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ListClubFaqInput = { club: string };
export type ListClubFaqOutput = Array<{ answer: string; club: string; id: string; question: string; rank: string }>;
export type ListClubFaqError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type MyAdminSchoolClubsInput = {  };
export type MyAdminSchoolClubsOutput = Array<{ club: { id: string; name: string } | null }>;
export type MyAdminSchoolClubsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type MyAppliesInput = {  };
export type MyAppliesOutput = Array<{ createdAt: string; id: string; recruitment: { club: { name: string } | null; id: string; title: string } | null; status: ApplyStatus }>;
export type MyAppliesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type MyApplyDraftsInput = {  };
export type MyApplyDraftsOutput = Array<{ id: string; recruitment: { id: string; period: { start: string; end: string }; title: string } | null; updatedAt: string }>;
export type MyApplyDraftsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type NoticeDetailInput = { notice: string };
export type NoticeDetailOutput = { author: { nickname: string } | null; body: string; createdAt: string; fixed: boolean; id: string; images: Array<{ image: string }>; title: string; version: number };
export type NoticeDetailError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOTICE_NOT_FOUND' };

export type RecruitmentAppliesInput = { r: string; status?: ApplyStatus | null };
export type RecruitmentAppliesOutput = Array<{ createdAt: string; id: string; member: { nickname: string } | null; status: ApplyStatus }>;
export type RecruitmentAppliesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' };

export type RecruitmentDetailInput = { r: string };
export type RecruitmentDetailOutput = { body: string; bookmarkCount: number; club: { id: string; name: string; profile: string | null; school: { name: string } | null } | null; externalUrl: string | null; field: Field; id: string; isMyApply: boolean; isMyClub: boolean; myLatestDraft: string | null; open: boolean; period: { start: string; end: string }; poster: string | null; region: Region; status: RecruitmentStatus; target: Target; title: string; views: number };
export type RecruitmentDetailError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' };

export type RecruitmentListInput = { filter: RecruitmentFilter; sort?: RecruitmentSort | null };
export type RecruitmentListOutput = Array<{ bookmarkCount: number; club: { affiliation: Affiliation; name: string } | null; field: Field; id: string; isBookmarked: boolean; period: { start: string; end: string }; poster: string | null; region: Region; target: Target; title: string }>;
export type RecruitmentListError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type RefuseRemainingStatusInput = { job: string };
export type RefuseRemainingStatusOutput = { createdAt: string; done: number; error: string | null; file: string | null; finishedAt: string | null; startedAt: string | null; status: JobStatus; total: number | null };
export type RefuseRemainingStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND' };

export type AddFinancialRecordInput = { club: string; at: string; amount: string; memo: string };
export type AddFinancialRecordOutput = null;
export type AddFinancialRecordError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type AnswerQuestionInput = { q: string; answer: string };
export type AnswerQuestionOutput = null;
export type AnswerQuestionError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_QUESTION_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'ALREADY_ANSWERED' };

export type ApproveAppliesInput = { applies: Array<string> };
export type ApproveAppliesOutput = null;
export type ApproveAppliesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_APPLIED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPLIES_FROM_DIFFERENT_CLUBS' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPLY_STATUS_INVALID_TRANSITION' };

export type ApproveFinancialSettlementInput = { financialRecord: string; comment?: string | null };
export type ApproveFinancialSettlementOutput = null;
export type ApproveFinancialSettlementError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'NOT_AN_APPROVER' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'SELF_APPROVAL_FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_VOTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_EXPIRED' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' };

export type ApproveRecruitmentInput = { r: string };
export type ApproveRecruitmentOutput = null;
export type ApproveRecruitmentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.OVERLAP'; reason: 'RECRUITMENT_PERIOD_OVERLAP' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'RECRUITMENT_STATUS_INVALID_TRANSITION' };

export type AskQuestionInput = { club: string; title: string; body: string };
export type AskQuestionOutput = null;
export type AskQuestionError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type BlockAuthorInput = { comment: string };
export type BlockAuthorOutput = null;
export type BlockAuthorError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_BLOCKED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'NOT_SELF' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ACTIVITY_COMMENT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'AUTHOR_UNAVAILABLE' };

export type CancelFinancialSettlementInput = { financialRecord: string };
export type CancelFinancialSettlementOutput = null;
export type CancelFinancialSettlementError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'ONLY_REQUESTER_CAN_CANCEL' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_EXPIRED' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' };

export type CancelSchoolAuthInput = {  };
export type CancelSchoolAuthOutput = null;
export type CancelSchoolAuthError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REGISTERED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'NICKNAME_TAKEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'ADMIN_OF_SCHOOL_CLUB' };

export type ChangeMemberRoleInput = { target: string; role: ClubRole };
export type ChangeMemberRoleOutput = null;
export type ChangeMemberRoleError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_MEMBER_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'CANNOT_CHANGE_OWN_ROLE' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'USE_ENTRUST_FOR_ADMIN' };

export type ChangeMemberStatusInput = { targets: Array<string>; newStatus: MemberStatus };
export type ChangeMemberStatusOutput = null;
export type ChangeMemberStatusError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_MEMBER_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'MEMBERS_FROM_DIFFERENT_CLUBS' };

export type CloseRecruitmentEarlyInput = { r: string };
export type CloseRecruitmentEarlyOutput = null;
export type CloseRecruitmentEarlyError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.OVERLAP'; reason: 'RECRUITMENT_PERIOD_OVERLAP' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'RECRUITMENT_NOT_OPEN' };

export type CreateClubInput = { input: ClubInput; adminName: string; profile?: Blob | null };
export type CreateClubOutput = { id: string; name: string };
export type CreateClubError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SCHOOL_MATCHES_AFFILIATION' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'SCHOOL_AUTH_REQUIRED' };

export type CreateClubEventInput = { club: string; title: string; at: string; place: string };
export type CreateClubEventOutput = { id: string };
export type CreateClubEventError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type CreateClubFaqInput = { club: string; question: string; answer: string };
export type CreateClubFaqOutput = { id: string };
export type CreateClubFaqError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type CreateRecruitmentInput = { club: string; input: RecruitmentInput; poster?: Blob | null };
export type CreateRecruitmentOutput = { id: string };
export type CreateRecruitmentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.OVERLAP'; reason: 'RECRUITMENT_PERIOD_OVERLAP' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NO_APPLY_FORM' };

export type DeleteActivityInput = { activity: string };
export type DeleteActivityOutput = null;
export type DeleteActivityError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_ACTIVITY_NOT_FOUND' };

export type DeleteApplyDraftInput = { draft: string };
export type DeleteApplyDraftOutput = null;
export type DeleteApplyDraftError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_DRAFT_NOT_FOUND' };

export type DeleteClubInput = { club: string };
export type DeleteClubOutput = null;
export type DeleteClubError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'ONLY_ADMIN_CAN_DELETE' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SCHOOL_MATCHES_AFFILIATION' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'CLUB_HAS_OTHER_MEMBERS' };

export type DeleteClubEventInput = { target: string };
export type DeleteClubEventOutput = null;
export type DeleteClubEventError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' };

export type DeleteClubFaqInput = { target: string };
export type DeleteClubFaqOutput = null;
export type DeleteClubFaqError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_FAQ_NOT_FOUND' };

export type DeleteCommentInput = { comment: string };
export type DeleteCommentOutput = null;
export type DeleteCommentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SAME_ACTIVITY' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ACTIVITY_COMMENT_NOT_FOUND' };

export type DeleteFinancialRecordInput = { record: string };
export type DeleteFinancialRecordOutput = null;
export type DeleteFinancialRecordError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' };

export type DeleteNoticeInput = { notice: string; noticeVersion: number };
export type DeleteNoticeOutput = null;
export type DeleteNoticeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_FIXED_NOTICES' }
  | { code: 'AIP.CONFLICT.STALE_VERSION'; reason: 'CLUB_NOTICE_VERSION_STALE' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOTICE_NOT_FOUND' };

export type DeleteRecruitmentInput = { r: string };
export type DeleteRecruitmentOutput = null;
export type DeleteRecruitmentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.OVERLAP'; reason: 'RECRUITMENT_PERIOD_OVERLAP' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'RECRUITMENT_HAS_APPLIES' };

export type EditActivityInput = { activity: string; access: AccessType; body: string; removeImages: Array<string>; addImages: Array<Blob> };
export type EditActivityOutput = null;
export type EditActivityError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_IMAGES' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ACTIVITY_IMAGE_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_ACTIVITY_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'IMAGE_NOT_IN_ACTIVITY' };

export type EditCommentInput = { comment: string; body: string };
export type EditCommentOutput = null;
export type EditCommentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SAME_ACTIVITY' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ACTIVITY_COMMENT_NOT_FOUND' };

export type EditFinancialRecordInput = { record: string; at: string; amount: string; memo: string };
export type EditFinancialRecordOutput = null;
export type EditFinancialRecordError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' };

export type EditNoticeInput = { notice: string; title: string; body: string; noticeVersion: number };
export type EditNoticeOutput = null;
export type EditNoticeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_FIXED_NOTICES' }
  | { code: 'AIP.CONFLICT.STALE_VERSION'; reason: 'CLUB_NOTICE_VERSION_STALE' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOTICE_NOT_FOUND' };

export type EntrustAdminInput = { target: string };
export type EntrustAdminOutput = null;
export type EntrustAdminError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_MEMBER_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'CANNOT_ENTRUST_TO_SELF' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'ENTRUST_TARGET_INACTIVE' };

export type ExportApplicantsInput = { recruitment: string };
export type ExportApplicantsOutput = { job: string; status: JobStatus };
export type ExportApplicantsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' };

export type ExportMyDataInput = {  };
export type ExportMyDataOutput = null;
export type ExportMyDataError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' };

export type IssueAttendanceCodeInput = { event: string };
export type IssueAttendanceCodeOutput = null;
export type IssueAttendanceCodeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' };

export type IssueClubInviteInput = { club: string };
export type IssueClubInviteOutput = null;
export type IssueClubInviteError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type IssueDirectInviteInput = { club: string; invitee: string };
export type IssueDirectInviteOutput = null;
export type IssueDirectInviteError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'MEMBER_NOT_FOUND' };

export type MarkAttendanceInput = { event: string; members: Array<string> };
export type MarkAttendanceOutput = null;
export type MarkAttendanceError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_ATTENDED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_MEMBER_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'MEMBER_NOT_IN_CLUB' };

export type MoveToInterviewInput = { applies: Array<string>; message: string };
export type MoveToInterviewOutput = null;
export type MoveToInterviewError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_APPLIED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPLIES_FROM_DIFFERENT_CLUBS' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPLY_STATUS_INVALID_TRANSITION' };

export type PostActivityInput = { club: string; access: AccessType; body: string; images: Array<Blob> };
export type PostActivityOutput = null;
export type PostActivityError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_IMAGES' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type PostCommentInput = { activity: string; parent?: string | null; body: string };
export type PostCommentOutput = null;
export type PostCommentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SAME_ACTIVITY' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ACTIVITY_COMMENT_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_ACTIVITY_NOT_FOUND' };

export type PostNoticeInput = { club: string; title: string; body: string; images: Array<Blob> };
export type PostNoticeOutput = null;
export type PostNoticeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_FIXED_NOTICES' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type QuitClubInput = { club: string };
export type QuitClubOutput = null;
export type QuitClubError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'ADMIN_MUST_ENTRUST_FIRST' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NOT_CLUB_MEMBER' };

export type RedeemAttendanceCodeInput = { token: string };
export type RedeemAttendanceCodeOutput = null;
export type RedeemAttendanceCodeError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_ATTENDED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'INVALID_GRANT_LINK' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NOT_CLUB_MEMBER' };

export type RedeemClubInviteInput = { token: string; name: string };
export type RedeemClubInviteOutput = null;
export type RedeemClubInviteError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'INVALID_GRANT_LINK' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'SCHOOL_MISMATCH' };

export type RedeemDirectInviteInput = { token: string; name: string };
export type RedeemDirectInviteOutput = null;
export type RedeemDirectInviteError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'INVALID_GRANT_LINK' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'SCHOOL_MISMATCH' };

export type RefuseAppliesInput = { applies: Array<string> };
export type RefuseAppliesOutput = null;
export type RefuseAppliesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_APPLIED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPLIES_FROM_DIFFERENT_CLUBS' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPLY_STATUS_INVALID_TRANSITION' };

export type RefuseRemainingInput = { recruitment: string };
export type RefuseRemainingOutput = { job: string; status: JobStatus };
export type RefuseRemainingError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' };

export type RejectFinancialSettlementInput = { financialRecord: string; reason?: string | null };
export type RejectFinancialSettlementOutput = null;
export type RejectFinancialSettlementError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'NOT_AN_APPROVER' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'SELF_APPROVAL_FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_VOTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_EXPIRED' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' };

export type RemoveClubMemberInput = { target: string };
export type RemoveClubMemberOutput = null;
export type RemoveClubMemberError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_MEMBER_NOT_FOUND' };

export type ReportContentInput = { target: { type: 'ClubReview' | 'PassReview' | 'ClubQuestion' | 'ActivityComment'; id: string }; reason: string };
export type ReportContentOutput = null;
export type ReportContentError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REPORTED' }
  | { code: 'AIP.INPUT.INVALID' };

export type RequestFinancialSettlementInput = { financialRecord: string };
export type RequestFinancialSettlementOutput = null;
export type RequestFinancialSettlementError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'APPROVAL_ALREADY_PENDING' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'FINANCIAL_RECORD_NOT_FOUND' };

export type RequestSchoolEmailInput = { target: string };
export type RequestSchoolEmailOutput = null;
export type RequestSchoolEmailError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'VERIFICATION_RESEND_TOO_SOON' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'VERIFICATION_TARGET_INVALID' };

export type ResolveReportInput = { report: string; remove: boolean };
export type ResolveReportOutput = null;
export type ResolveReportError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REPORTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SAME_ACTIVITY' }
  | { code: 'AIP.NOT_FOUND'; reason: 'REPORT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'REPORT_STATUS_INVALID_TRANSITION' };

export type SaveApplyDraftInput = { r: string; answers: unknown; portfolioUrl?: string | null; file?: Blob | null };
export type SaveApplyDraftOutput = { id: string };
export type SaveApplyDraftError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'RECRUITMENT_CLOSED' };

export type SubmitApplyInput = { r: string; answers: unknown; portfolioUrl?: string | null; file?: Blob | null };
export type SubmitApplyOutput = { id: string; status: ApplyStatus };
export type SubmitApplyError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_APPLIED' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'RECRUITMENT_CLOSED' };

export type ToggleActivityLikeInput = { activity: string };
export type ToggleActivityLikeOutput = null;
export type ToggleActivityLikeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_LIKED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_ACTIVITY_NOT_FOUND' };

export type ToggleClubBookmarkInput = { club: string };
export type ToggleClubBookmarkOutput = null;
export type ToggleClubBookmarkError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_BOOKMARKED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type ToggleCommentLikeInput = { comment: string };
export type ToggleCommentLikeOutput = null;
export type ToggleCommentLikeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_LIKED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ACTIVITY_COMMENT_NOT_FOUND' };

export type ToggleNoticeFixedInput = { notice: string; noticeVersion: number };
export type ToggleNoticeFixedOutput = null;
export type ToggleNoticeFixedError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_FIXED_NOTICES' }
  | { code: 'AIP.CONFLICT.STALE_VERSION'; reason: 'CLUB_NOTICE_VERSION_STALE' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOTICE_NOT_FOUND' };

export type ToggleRecruitmentBookmarkInput = { r: string };
export type ToggleRecruitmentBookmarkOutput = null;
export type ToggleRecruitmentBookmarkError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_BOOKMARKED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' };

export type UnmarkAttendanceInput = { event: string; members: Array<string> };
export type UnmarkAttendanceOutput = null;
export type UnmarkAttendanceError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_ATTENDED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_MEMBER_NOT_FOUND' };

export type UnregisterInput = {  };
export type UnregisterOutput = null;
export type UnregisterError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.CAPACITY'; reason: 'TOO_MANY_FIXED_NOTICES' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_APPLIED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_ATTENDED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_BLOCKED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_BOOKMARKED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_CLUB_MEMBER' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_LIKED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REGISTERED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REPORTED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'NICKNAME_TAKEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'CLUB_MEMBER_EXACTLY_ONE' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'NOT_SELF' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SAME_ACTIVITY' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SCHOOL_MATCHES_AFFILIATION' };

export type UpdateApplyDraftInput = { draft: string; answers: unknown; portfolioUrl?: string | null; file?: Blob | null };
export type UpdateApplyDraftOutput = null;
export type UpdateApplyDraftError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_DRAFT_NOT_FOUND' };

export type UpdateApplyFormInput = { club: string; questions: Array<Question> };
export type UpdateApplyFormOutput = null;
export type UpdateApplyFormError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type UpdateClubInput = { club: string; input: ClubInput; profile?: Blob | null; banner?: Blob | null };
export type UpdateClubOutput = null;
export type UpdateClubError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.INVARIANT.VIOLATED'; reason: 'SCHOOL_MATCHES_AFFILIATION' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'AFFILIATION_IMMUTABLE' };

export type UpdateClubEventInput = { target: string; title: string; at: string; place: string };
export type UpdateClubEventOutput = null;
export type UpdateClubEventError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_EVENT_NOT_FOUND' };

export type UpdateClubFaqInput = { target: string; question: string; answer: string };
export type UpdateClubFaqOutput = null;
export type UpdateClubFaqError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_FAQ_NOT_FOUND' };

export type VerifySchoolEmailInput = { target: string; code: string };
export type VerifySchoolEmailOutput = null;
export type VerifySchoolEmailError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_REGISTERED' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'NICKNAME_TAKEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'VERIFICATION_CODE_MISMATCH' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'VERIFICATION_NOT_FOUND' };

export type WithdrawApplyInput = { apply: string };
export type WithdrawApplyOutput = null;
export type WithdrawApplyError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_APPLIED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'APPLY_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'WITHDRAW_TOO_EARLY' };

export type WriteClubReviewInput = { club: string; title: string; body: string; tags: Array<string> };
export type WriteClubReviewOutput = null;
export type WriteClubReviewError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'CLUB_NOT_FOUND' };

export type WritePassReviewInput = { r: string; title: string; body: string; generation: number };
export type WritePassReviewOutput = null;
export type WritePassReviewError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'RECRUITMENT_NOT_FOUND' };

export interface AipErrorBody {
  code: string;
  intent: string;
  reason?: string;
  path?: string;
  message: string;
  retryable: boolean;
}

/** Thrown for every failed call; `body` is narrowed per intent by the generated error unions. */
export class AipError<E = { code: string }> extends Error {
  readonly body: AipErrorBody & E;
  readonly status: number;
  constructor(status: number, body: AipErrorBody & E) {
    super(`${body.code}${body.reason ? ` (${body.reason})` : ''}: ${body.message}`);
    this.status = status;
    this.body = body;
  }
}

export interface ClientOptions {
  baseUrl: string;
  /** Bearer token, or a function returning one (for refresh). */
  token?: string | (() => string | undefined | Promise<string | undefined>);
  fetch?: typeof fetch;
}

export interface PageRequest {
  cursor?: string | null;
  page?: number;
}

export interface Page {
  next_cursor?: string | null;
  has_more: boolean;
}

export interface Result<O> {
  data: O;
  page?: Page;
  items?: Array<{ index: number; ok: boolean; error?: AipErrorBody }>;
}

/** Replaces Blob values with part names and collects the files for multipart upload. */
function extractFiles(value: unknown, files: Map<string, Blob>): unknown {
  if (typeof Blob !== 'undefined' && value instanceof Blob) {
    const name = `file${files.size}`;
    files.set(name, value);
    return name;
  }
  if (Array.isArray(value)) return value.map((v) => extractFiles(v, files));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, extractFiles(v, files)]));
  }
  return value;
}

function makeCall(opts: ClientOptions) {
  const f = opts.fetch ?? fetch;
  return async function call<O, E>(intent: string, input: unknown, idempotencyKey?: string): Promise<Result<O>> {
    const headers: Record<string, string> = {};
    const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
    if (token) headers['authorization'] = `Bearer ${token}`;
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const files = new Map<string, Blob>();
    const payload = extractFiles(input, files);
    let body: BodyInit;
    if (files.size > 0) {
      const form = new FormData();
      form.append('input', JSON.stringify(payload));
      for (const [name, blob] of files) form.append(name, blob, (blob as File).name ?? name);
      body = form;
    } else {
      headers['content-type'] = 'application/json';
      body = JSON.stringify(payload);
    }
    const res = await f(`${opts.baseUrl}/aip/${intent}`, { method: 'POST', headers, body });
    const json = (await res.json()) as { data?: O; page?: Page; items?: Result<O>['items']; error?: AipErrorBody };
    if (!res.ok || json.error) throw new AipError<E>(res.status, json.error as AipErrorBody & E);
    return { data: json.data as O, page: json.page, items: json.items };
  };
}

export function createClient(opts: ClientOptions) {
  const call = makeCall(opts);
  return {
    queries: {
      ActivityDetail: (input: ActivityDetailInput) => call<ActivityDetailOutput, ActivityDetailError>('ActivityDetail', input),
      ApplyDetail: (input: ApplyDetailInput) => call<ApplyDetailOutput, ApplyDetailError>('ApplyDetail', input),
      ClubActiveRecruitment: (input: ClubActiveRecruitmentInput, page?: PageRequest) => call<ClubActiveRecruitmentOutput, ClubActiveRecruitmentError>('ClubActiveRecruitment', { ...input, ...(page ?? {}) }),
      ClubActivities: (input: ClubActivitiesInput, page?: PageRequest) => call<ClubActivitiesOutput, ClubActivitiesError>('ClubActivities', { ...input, ...(page ?? {}) }),
      ClubBalance: (input: ClubBalanceInput) => call<ClubBalanceOutput, ClubBalanceError>('ClubBalance', input),
      ClubDetail: (input: ClubDetailInput) => call<ClubDetailOutput, ClubDetailError>('ClubDetail', input),
      ClubList: (input: ClubListInput, page?: PageRequest) => call<ClubListOutput, ClubListError>('ClubList', { ...input, ...(page ?? {}) }),
      ClubMembers: (input: ClubMembersInput, page?: PageRequest) => call<ClubMembersOutput, ClubMembersError>('ClubMembers', { ...input, ...(page ?? {}) }),
      ClubNotices: (input: ClubNoticesInput, page?: PageRequest) => call<ClubNoticesOutput, ClubNoticesError>('ClubNotices', { ...input, ...(page ?? {}) }),
      ClubQuestions: (input: ClubQuestionsInput, page?: PageRequest) => call<ClubQuestionsOutput, ClubQuestionsError>('ClubQuestions', { ...input, ...(page ?? {}) }),
      EventAttendees: (input: EventAttendeesInput, page?: PageRequest) => call<EventAttendeesOutput, EventAttendeesError>('EventAttendees', { ...input, ...(page ?? {}) }),
      ExportApplicantsStatus: (input: ExportApplicantsStatusInput) => call<ExportApplicantsStatusOutput, ExportApplicantsStatusError>('ExportApplicantsStatus', input),
      FinancialLedger: (input: FinancialLedgerInput, page?: PageRequest) => call<FinancialLedgerOutput, FinancialLedgerError>('FinancialLedger', { ...input, ...(page ?? {}) }),
      FinancialSettlementStatus: (input: FinancialSettlementStatusInput) => call<FinancialSettlementStatusOutput, FinancialSettlementStatusError>('FinancialSettlementStatus', input),
      GetClubEvent: (input: GetClubEventInput) => call<GetClubEventOutput, GetClubEventError>('GetClubEvent', input),
      GetClubFaq: (input: GetClubFaqInput) => call<GetClubFaqOutput, GetClubFaqError>('GetClubFaq', input),
      ListClubEvent: (input: ListClubEventInput, page?: PageRequest) => call<ListClubEventOutput, ListClubEventError>('ListClubEvent', { ...input, ...(page ?? {}) }),
      ListClubFaq: (input: ListClubFaqInput, page?: PageRequest) => call<ListClubFaqOutput, ListClubFaqError>('ListClubFaq', { ...input, ...(page ?? {}) }),
      MyAdminSchoolClubs: (input: MyAdminSchoolClubsInput, page?: PageRequest) => call<MyAdminSchoolClubsOutput, MyAdminSchoolClubsError>('MyAdminSchoolClubs', { ...input, ...(page ?? {}) }),
      MyApplies: (input: MyAppliesInput, page?: PageRequest) => call<MyAppliesOutput, MyAppliesError>('MyApplies', { ...input, ...(page ?? {}) }),
      MyApplyDrafts: (input: MyApplyDraftsInput, page?: PageRequest) => call<MyApplyDraftsOutput, MyApplyDraftsError>('MyApplyDrafts', { ...input, ...(page ?? {}) }),
      NoticeDetail: (input: NoticeDetailInput) => call<NoticeDetailOutput, NoticeDetailError>('NoticeDetail', input),
      RecruitmentApplies: (input: RecruitmentAppliesInput, page?: PageRequest) => call<RecruitmentAppliesOutput, RecruitmentAppliesError>('RecruitmentApplies', { ...input, ...(page ?? {}) }),
      RecruitmentDetail: (input: RecruitmentDetailInput) => call<RecruitmentDetailOutput, RecruitmentDetailError>('RecruitmentDetail', input),
      RecruitmentList: (input: RecruitmentListInput, page?: PageRequest) => call<RecruitmentListOutput, RecruitmentListError>('RecruitmentList', { ...input, ...(page ?? {}) }),
      RefuseRemainingStatus: (input: RefuseRemainingStatusInput) => call<RefuseRemainingStatusOutput, RefuseRemainingStatusError>('RefuseRemainingStatus', input),
    },
    commands: {
      AddFinancialRecord: (input: AddFinancialRecordInput) => call<AddFinancialRecordOutput, AddFinancialRecordError>('AddFinancialRecord', input),
      AnswerQuestion: (input: AnswerQuestionInput) => call<AnswerQuestionOutput, AnswerQuestionError>('AnswerQuestion', input),
      ApproveApplies: (input: ApproveAppliesInput) => call<ApproveAppliesOutput, ApproveAppliesError>('ApproveApplies', input),
      ApproveFinancialSettlement: (input: ApproveFinancialSettlementInput) => call<ApproveFinancialSettlementOutput, ApproveFinancialSettlementError>('ApproveFinancialSettlement', input),
      ApproveRecruitment: (input: ApproveRecruitmentInput) => call<ApproveRecruitmentOutput, ApproveRecruitmentError>('ApproveRecruitment', input),
      AskQuestion: (input: AskQuestionInput) => call<AskQuestionOutput, AskQuestionError>('AskQuestion', input),
      BlockAuthor: (input: BlockAuthorInput) => call<BlockAuthorOutput, BlockAuthorError>('BlockAuthor', input),
      CancelFinancialSettlement: (input: CancelFinancialSettlementInput) => call<CancelFinancialSettlementOutput, CancelFinancialSettlementError>('CancelFinancialSettlement', input),
      CancelSchoolAuth: (input: CancelSchoolAuthInput) => call<CancelSchoolAuthOutput, CancelSchoolAuthError>('CancelSchoolAuth', input),
      ChangeMemberRole: (input: ChangeMemberRoleInput) => call<ChangeMemberRoleOutput, ChangeMemberRoleError>('ChangeMemberRole', input),
      ChangeMemberStatus: (input: ChangeMemberStatusInput) => call<ChangeMemberStatusOutput, ChangeMemberStatusError>('ChangeMemberStatus', input),
      CloseRecruitmentEarly: (input: CloseRecruitmentEarlyInput) => call<CloseRecruitmentEarlyOutput, CloseRecruitmentEarlyError>('CloseRecruitmentEarly', input),
      CreateClub: (input: CreateClubInput, o: { idempotencyKey: string }) => call<CreateClubOutput, CreateClubError>('CreateClub', input, o.idempotencyKey),
      CreateClubEvent: (input: CreateClubEventInput, o: { idempotencyKey: string }) => call<CreateClubEventOutput, CreateClubEventError>('CreateClubEvent', input, o.idempotencyKey),
      CreateClubFaq: (input: CreateClubFaqInput, o: { idempotencyKey: string }) => call<CreateClubFaqOutput, CreateClubFaqError>('CreateClubFaq', input, o.idempotencyKey),
      CreateRecruitment: (input: CreateRecruitmentInput, o: { idempotencyKey: string }) => call<CreateRecruitmentOutput, CreateRecruitmentError>('CreateRecruitment', input, o.idempotencyKey),
      DeleteActivity: (input: DeleteActivityInput) => call<DeleteActivityOutput, DeleteActivityError>('DeleteActivity', input),
      DeleteApplyDraft: (input: DeleteApplyDraftInput) => call<DeleteApplyDraftOutput, DeleteApplyDraftError>('DeleteApplyDraft', input),
      DeleteClub: (input: DeleteClubInput) => call<DeleteClubOutput, DeleteClubError>('DeleteClub', input),
      DeleteClubEvent: (input: DeleteClubEventInput) => call<DeleteClubEventOutput, DeleteClubEventError>('DeleteClubEvent', input),
      DeleteClubFaq: (input: DeleteClubFaqInput) => call<DeleteClubFaqOutput, DeleteClubFaqError>('DeleteClubFaq', input),
      DeleteComment: (input: DeleteCommentInput) => call<DeleteCommentOutput, DeleteCommentError>('DeleteComment', input),
      DeleteFinancialRecord: (input: DeleteFinancialRecordInput) => call<DeleteFinancialRecordOutput, DeleteFinancialRecordError>('DeleteFinancialRecord', input),
      DeleteNotice: (input: DeleteNoticeInput) => call<DeleteNoticeOutput, DeleteNoticeError>('DeleteNotice', input),
      DeleteRecruitment: (input: DeleteRecruitmentInput) => call<DeleteRecruitmentOutput, DeleteRecruitmentError>('DeleteRecruitment', input),
      EditActivity: (input: EditActivityInput) => call<EditActivityOutput, EditActivityError>('EditActivity', input),
      EditComment: (input: EditCommentInput) => call<EditCommentOutput, EditCommentError>('EditComment', input),
      EditFinancialRecord: (input: EditFinancialRecordInput) => call<EditFinancialRecordOutput, EditFinancialRecordError>('EditFinancialRecord', input),
      EditNotice: (input: EditNoticeInput) => call<EditNoticeOutput, EditNoticeError>('EditNotice', input),
      EntrustAdmin: (input: EntrustAdminInput) => call<EntrustAdminOutput, EntrustAdminError>('EntrustAdmin', input),
      ExportApplicants: (input: ExportApplicantsInput) => call<ExportApplicantsOutput, ExportApplicantsError>('ExportApplicants', input),
      ExportMyData: (input: ExportMyDataInput) => call<ExportMyDataOutput, ExportMyDataError>('ExportMyData', input),
      IssueAttendanceCode: (input: IssueAttendanceCodeInput) => call<IssueAttendanceCodeOutput, IssueAttendanceCodeError>('IssueAttendanceCode', input),
      IssueClubInvite: (input: IssueClubInviteInput) => call<IssueClubInviteOutput, IssueClubInviteError>('IssueClubInvite', input),
      IssueDirectInvite: (input: IssueDirectInviteInput) => call<IssueDirectInviteOutput, IssueDirectInviteError>('IssueDirectInvite', input),
      MarkAttendance: (input: MarkAttendanceInput) => call<MarkAttendanceOutput, MarkAttendanceError>('MarkAttendance', input),
      MoveToInterview: (input: MoveToInterviewInput) => call<MoveToInterviewOutput, MoveToInterviewError>('MoveToInterview', input),
      PostActivity: (input: PostActivityInput, o: { idempotencyKey: string }) => call<PostActivityOutput, PostActivityError>('PostActivity', input, o.idempotencyKey),
      PostComment: (input: PostCommentInput, o: { idempotencyKey: string }) => call<PostCommentOutput, PostCommentError>('PostComment', input, o.idempotencyKey),
      PostNotice: (input: PostNoticeInput, o: { idempotencyKey: string }) => call<PostNoticeOutput, PostNoticeError>('PostNotice', input, o.idempotencyKey),
      QuitClub: (input: QuitClubInput) => call<QuitClubOutput, QuitClubError>('QuitClub', input),
      RedeemAttendanceCode: (input: RedeemAttendanceCodeInput) => call<RedeemAttendanceCodeOutput, RedeemAttendanceCodeError>('RedeemAttendanceCode', input),
      RedeemClubInvite: (input: RedeemClubInviteInput) => call<RedeemClubInviteOutput, RedeemClubInviteError>('RedeemClubInvite', input),
      RedeemDirectInvite: (input: RedeemDirectInviteInput) => call<RedeemDirectInviteOutput, RedeemDirectInviteError>('RedeemDirectInvite', input),
      RefuseApplies: (input: RefuseAppliesInput) => call<RefuseAppliesOutput, RefuseAppliesError>('RefuseApplies', input),
      RefuseRemaining: (input: RefuseRemainingInput) => call<RefuseRemainingOutput, RefuseRemainingError>('RefuseRemaining', input),
      RejectFinancialSettlement: (input: RejectFinancialSettlementInput) => call<RejectFinancialSettlementOutput, RejectFinancialSettlementError>('RejectFinancialSettlement', input),
      RemoveClubMember: (input: RemoveClubMemberInput) => call<RemoveClubMemberOutput, RemoveClubMemberError>('RemoveClubMember', input),
      ReportContent: (input: ReportContentInput) => call<ReportContentOutput, ReportContentError>('ReportContent', input),
      RequestFinancialSettlement: (input: RequestFinancialSettlementInput) => call<RequestFinancialSettlementOutput, RequestFinancialSettlementError>('RequestFinancialSettlement', input),
      RequestSchoolEmail: (input: RequestSchoolEmailInput) => call<RequestSchoolEmailOutput, RequestSchoolEmailError>('RequestSchoolEmail', input),
      ResolveReport: (input: ResolveReportInput) => call<ResolveReportOutput, ResolveReportError>('ResolveReport', input),
      SaveApplyDraft: (input: SaveApplyDraftInput, o: { idempotencyKey: string }) => call<SaveApplyDraftOutput, SaveApplyDraftError>('SaveApplyDraft', input, o.idempotencyKey),
      SubmitApply: (input: SubmitApplyInput, o: { idempotencyKey: string }) => call<SubmitApplyOutput, SubmitApplyError>('SubmitApply', input, o.idempotencyKey),
      ToggleActivityLike: (input: ToggleActivityLikeInput) => call<ToggleActivityLikeOutput, ToggleActivityLikeError>('ToggleActivityLike', input),
      ToggleClubBookmark: (input: ToggleClubBookmarkInput) => call<ToggleClubBookmarkOutput, ToggleClubBookmarkError>('ToggleClubBookmark', input),
      ToggleCommentLike: (input: ToggleCommentLikeInput) => call<ToggleCommentLikeOutput, ToggleCommentLikeError>('ToggleCommentLike', input),
      ToggleNoticeFixed: (input: ToggleNoticeFixedInput) => call<ToggleNoticeFixedOutput, ToggleNoticeFixedError>('ToggleNoticeFixed', input),
      ToggleRecruitmentBookmark: (input: ToggleRecruitmentBookmarkInput) => call<ToggleRecruitmentBookmarkOutput, ToggleRecruitmentBookmarkError>('ToggleRecruitmentBookmark', input),
      UnmarkAttendance: (input: UnmarkAttendanceInput) => call<UnmarkAttendanceOutput, UnmarkAttendanceError>('UnmarkAttendance', input),
      Unregister: (input: UnregisterInput) => call<UnregisterOutput, UnregisterError>('Unregister', input),
      UpdateApplyDraft: (input: UpdateApplyDraftInput) => call<UpdateApplyDraftOutput, UpdateApplyDraftError>('UpdateApplyDraft', input),
      UpdateApplyForm: (input: UpdateApplyFormInput) => call<UpdateApplyFormOutput, UpdateApplyFormError>('UpdateApplyForm', input),
      UpdateClub: (input: UpdateClubInput) => call<UpdateClubOutput, UpdateClubError>('UpdateClub', input),
      UpdateClubEvent: (input: UpdateClubEventInput) => call<UpdateClubEventOutput, UpdateClubEventError>('UpdateClubEvent', input),
      UpdateClubFaq: (input: UpdateClubFaqInput) => call<UpdateClubFaqOutput, UpdateClubFaqError>('UpdateClubFaq', input),
      VerifySchoolEmail: (input: VerifySchoolEmailInput) => call<VerifySchoolEmailOutput, VerifySchoolEmailError>('VerifySchoolEmail', input),
      WithdrawApply: (input: WithdrawApplyInput) => call<WithdrawApplyOutput, WithdrawApplyError>('WithdrawApply', input),
      WriteClubReview: (input: WriteClubReviewInput) => call<WriteClubReviewOutput, WriteClubReviewError>('WriteClubReview', input),
      WritePassReview: (input: WritePassReviewInput) => call<WritePassReviewOutput, WritePassReviewError>('WritePassReview', input),
    },
  };
}
