// Generated by `aip gen ts` from the AIP contract aip-protocol/0.1 (core aip-core/0.11). Do not edit.
/* eslint-disable */

export type ApprovalDecision = 'APPROVE' | 'REJECT';
export type ApprovalStatus = 'NONE' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'EXPIRED';
export type ConsentStatus = 'NONE' | 'GIVEN' | 'OUTDATED' | 'WITHDRAWN';
export type MemberRole = 'USER' | 'SUPPORT' | 'ROOT';


export type ArticleDraftsInput = { site: string };
export type ArticleDraftsOutput = Array<{ body: string; id: string; reviewed: boolean; title: string }>;
export type ArticleDraftsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.CONSENT.REQUIRED'; reason: 'Terms' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'SITE_NOT_FOUND' };

export type ArticleReviewStatusInput = { article: string };
export type ArticleReviewStatusOutput = { approvals: number; canVote: boolean; decidedAt: string | null; expiresAt: string | null; requestedAt: string | null; requestedBy: string | null; required: number; status: ApprovalStatus; votes: Array<{ at: string; comment: string | null; decision: ApprovalDecision; voter: string }> };
export type ArticleReviewStatusError =
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' };

export type ArticlesInput = { site: string };
export type ArticlesOutput = Array<{ body: string; id: string; title: string }>;
export type ArticlesError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'SITE_NOT_FOUND' };

export type GetArticleInput = { article: string };
export type GetArticleOutput = { body: string; id: string; title: string };
export type GetArticleError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' };

export type TermsConsentStatusInput = {  };
export type TermsConsentStatusOutput = { givenAt: string | null; givenVersion: number | null; name: string; status: ConsentStatus; version: number; withdrawnAt: string | null };
export type TermsConsentStatusError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.INPUT.INVALID' };

export type AddEditorInput = { site: string; member: string };
export type AddEditorOutput = null;
export type AddEditorError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_EDITOR' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'MEMBER_NOT_FOUND' }
  | { code: 'AIP.NOT_FOUND'; reason: 'SITE_NOT_FOUND' };

export type ApproveArticleReviewInput = { article: string; comment?: string | null };
export type ApproveArticleReviewOutput = null;
export type ApproveArticleReviewError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_FORBIDDEN' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'NOT_AN_APPROVER' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_VOTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type CancelArticleReviewInput = { article: string };
export type CancelArticleReviewOutput = null;
export type CancelArticleReviewError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'ONLY_REQUESTER_CAN_CANCEL' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' };

export type CreateArticleInput = { site: string; title: string; body: string };
export type CreateArticleOutput = { id: string; title: string };
export type CreateArticleError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONSENT.REQUIRED'; reason: 'Terms' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'SITE_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type CreateSiteInput = { name: string };
export type CreateSiteOutput = { id: string; name: string };
export type CreateSiteError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_EDITOR' }
  | { code: 'AIP.IDEMPOTENCY.KEY_REUSED' }
  | { code: 'AIP.INPUT.INVALID' };

export type DeleteArticleInput = { article: string };
export type DeleteArticleOutput = null;
export type DeleteArticleError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type DeleteMyAccountInput = {  };
export type DeleteMyAccountOutput = null;
export type DeleteMyAccountError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_EDITOR' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'EMAIL_TAKEN' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type DiscardArticleDraftInput = { article: string };
export type DiscardArticleDraftOutput = null;
export type DiscardArticleDraftError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'NOT_PUBLISHED' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type EditArticleInput = { article: string; title: string; body: string };
export type EditArticleOutput = null;
export type EditArticleError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type ExportMyDataInput = {  };
export type ExportMyDataOutput = null;
export type ExportMyDataError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' };

export type GiveTermsConsentInput = {  };
export type GiveTermsConsentOutput = { givenAt: string | null; givenVersion: number | null; name: string; status: ConsentStatus; version: number; withdrawnAt: string | null };
export type GiveTermsConsentError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' };

export type PublishArticleInput = { article: string };
export type PublishArticleOutput = { publishedAt: string };
export type PublishArticleError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' };

export type PurgeDraftsInput = { site: string };
export type PurgeDraftsOutput = null;
export type PurgeDraftsError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'SITE_NOT_FOUND' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type RejectArticleReviewInput = { article: string; reason?: string | null };
export type RejectArticleReviewOutput = null;
export type RejectArticleReviewError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_FORBIDDEN' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'NOT_AN_APPROVER' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'ALREADY_VOTED' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' }
  | { code: 'AIP.PRECONDITION.FAILED'; reason: 'APPROVAL_NOT_PENDING' }
  | { code: 'AIP.TENANT.MISMATCH' };

export type RenameMeInput = { name: string };
export type RenameMeOutput = null;
export type RenameMeError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'EMAIL_TAKEN' }
  | { code: 'AIP.INPUT.INVALID' };

export type RequestArticleReviewInput = { article: string };
export type RequestArticleReviewOutput = null;
export type RequestArticleReviewError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.CONFLICT.UNIQUE'; reason: 'APPROVAL_ALREADY_PENDING' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'ARTICLE_NOT_FOUND' };

export type StartMemberImpersonationInput = { target: string; reason: string };
export type StartMemberImpersonationOutput = { expiresAt: string; session: string; target: string; token: string };
export type StartMemberImpersonationError =
  | { code: 'AIP.AUTH.FORBIDDEN' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_NESTED' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_SELF' }
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_TARGET_PRIVILEGED' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' }
  | { code: 'AIP.NOT_FOUND'; reason: 'MEMBER_NOT_FOUND' };

export type StopMemberImpersonationInput = {  };
export type StopMemberImpersonationOutput = { ended: number };
export type StopMemberImpersonationError =
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' };

export type WithdrawTermsConsentInput = {  };
export type WithdrawTermsConsentOutput = { givenAt: string | null; givenVersion: number | null; name: string; status: ConsentStatus; version: number; withdrawnAt: string | null };
export type WithdrawTermsConsentError =
  | { code: 'AIP.AUTH.FORBIDDEN'; reason: 'IMPERSONATION_FORBIDDEN' }
  | { code: 'AIP.AUTH.UNAUTHENTICATED' }
  | { code: 'AIP.CONCURRENCY.CONFLICT' }
  | { code: 'AIP.INPUT.INVALID' };

export interface AipErrorBody {
  code: string;
  intent: string;
  reason?: string;
  path?: string;
  message: string;
  retryable: boolean;
}

/** Thrown for every failed call; `body` is narrowed per intent by the generated error unions. */
export class AipError<E = { code: string }> extends Error {
  readonly body: AipErrorBody & E;
  readonly status: number;
  constructor(status: number, body: AipErrorBody & E) {
    super(`${body.code}${body.reason ? ` (${body.reason})` : ''}: ${body.message}`);
    this.status = status;
    this.body = body;
  }
}

export interface ClientOptions {
  baseUrl: string;
  /** Bearer token, or a function returning one (for refresh). */
  token?: string | (() => string | undefined | Promise<string | undefined>);
  fetch?: typeof fetch;
}

export interface PageRequest {
  cursor?: string | null;
  page?: number;
}

export interface Page {
  next_cursor?: string | null;
  has_more: boolean;
}

export interface Result<O> {
  data: O;
  page?: Page;
  items?: Array<{ index: number; ok: boolean; error?: AipErrorBody }>;
}

/** Replaces Blob values with part names and collects the files for multipart upload. */
function extractFiles(value: unknown, files: Map<string, Blob>): unknown {
  if (typeof Blob !== 'undefined' && value instanceof Blob) {
    const name = `file${files.size}`;
    files.set(name, value);
    return name;
  }
  if (Array.isArray(value)) return value.map((v) => extractFiles(v, files));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, extractFiles(v, files)]));
  }
  return value;
}

function makeCall(opts: ClientOptions) {
  const f = opts.fetch ?? fetch;
  return async function call<O, E>(intent: string, input: unknown, idempotencyKey?: string): Promise<Result<O>> {
    const headers: Record<string, string> = {};
    const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
    if (token) headers['authorization'] = `Bearer ${token}`;
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const files = new Map<string, Blob>();
    const payload = extractFiles(input, files);
    let body: BodyInit;
    if (files.size > 0) {
      const form = new FormData();
      form.append('input', JSON.stringify(payload));
      for (const [name, blob] of files) form.append(name, blob, (blob as File).name ?? name);
      body = form;
    } else {
      headers['content-type'] = 'application/json';
      body = JSON.stringify(payload);
    }
    const res = await f(`${opts.baseUrl}/aip/${intent}`, { method: 'POST', headers, body });
    const json = (await res.json()) as { data?: O; page?: Page; items?: Result<O>['items']; error?: AipErrorBody };
    if (!res.ok || json.error) throw new AipError<E>(res.status, json.error as AipErrorBody & E);
    return { data: json.data as O, page: json.page, items: json.items };
  };
}

export function createClient(opts: ClientOptions) {
  const call = makeCall(opts);
  return {
    queries: {
      ArticleDrafts: (input: ArticleDraftsInput, page?: PageRequest) => call<ArticleDraftsOutput, ArticleDraftsError>('ArticleDrafts', { ...input, ...(page ?? {}) }),
      ArticleReviewStatus: (input: ArticleReviewStatusInput) => call<ArticleReviewStatusOutput, ArticleReviewStatusError>('ArticleReviewStatus', input),
      Articles: (input: ArticlesInput, page?: PageRequest) => call<ArticlesOutput, ArticlesError>('Articles', { ...input, ...(page ?? {}) }),
      GetArticle: (input: GetArticleInput) => call<GetArticleOutput, GetArticleError>('GetArticle', input),
      TermsConsentStatus: (input: TermsConsentStatusInput) => call<TermsConsentStatusOutput, TermsConsentStatusError>('TermsConsentStatus', input),
    },
    commands: {
      AddEditor: (input: AddEditorInput) => call<AddEditorOutput, AddEditorError>('AddEditor', input),
      ApproveArticleReview: (input: ApproveArticleReviewInput) => call<ApproveArticleReviewOutput, ApproveArticleReviewError>('ApproveArticleReview', input),
      CancelArticleReview: (input: CancelArticleReviewInput) => call<CancelArticleReviewOutput, CancelArticleReviewError>('CancelArticleReview', input),
      CreateArticle: (input: CreateArticleInput, o: { idempotencyKey: string }) => call<CreateArticleOutput, CreateArticleError>('CreateArticle', input, o.idempotencyKey),
      CreateSite: (input: CreateSiteInput, o: { idempotencyKey: string }) => call<CreateSiteOutput, CreateSiteError>('CreateSite', input, o.idempotencyKey),
      DeleteArticle: (input: DeleteArticleInput) => call<DeleteArticleOutput, DeleteArticleError>('DeleteArticle', input),
      DeleteMyAccount: (input: DeleteMyAccountInput) => call<DeleteMyAccountOutput, DeleteMyAccountError>('DeleteMyAccount', input),
      DiscardArticleDraft: (input: DiscardArticleDraftInput) => call<DiscardArticleDraftOutput, DiscardArticleDraftError>('DiscardArticleDraft', input),
      EditArticle: (input: EditArticleInput) => call<EditArticleOutput, EditArticleError>('EditArticle', input),
      ExportMyData: (input: ExportMyDataInput) => call<ExportMyDataOutput, ExportMyDataError>('ExportMyData', input),
      GiveTermsConsent: (input: GiveTermsConsentInput) => call<GiveTermsConsentOutput, GiveTermsConsentError>('GiveTermsConsent', input),
      PublishArticle: (input: PublishArticleInput) => call<PublishArticleOutput, PublishArticleError>('PublishArticle', input),
      PurgeDrafts: (input: PurgeDraftsInput) => call<PurgeDraftsOutput, PurgeDraftsError>('PurgeDrafts', input),
      RejectArticleReview: (input: RejectArticleReviewInput) => call<RejectArticleReviewOutput, RejectArticleReviewError>('RejectArticleReview', input),
      RenameMe: (input: RenameMeInput) => call<RenameMeOutput, RenameMeError>('RenameMe', input),
      RequestArticleReview: (input: RequestArticleReviewInput) => call<RequestArticleReviewOutput, RequestArticleReviewError>('RequestArticleReview', input),
      StartMemberImpersonation: (input: StartMemberImpersonationInput) => call<StartMemberImpersonationOutput, StartMemberImpersonationError>('StartMemberImpersonation', input),
      StopMemberImpersonation: (input: StopMemberImpersonationInput) => call<StopMemberImpersonationOutput, StopMemberImpersonationError>('StopMemberImpersonation', input),
      WithdrawTermsConsent: (input: WithdrawTermsConsentInput) => call<WithdrawTermsConsentOutput, WithdrawTermsConsentError>('WithdrawTermsConsent', input),
    },
  };
}
