//! Contract → TypeScript client. Works from the `describe` JSON only, so any
//! consumer that can fetch `/aip/describe` can produce the same client.

use serde_json::Value;
use std::fmt::Write;

fn pascal(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == '.' {
            up = true;
        } else if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn ts_type(v: &Value) -> String {
    let base = match v.get("kind").and_then(|k| k.as_str()).unwrap_or("unknown") {
        "bool" => "boolean".to_string(),
        "int" => "number".to_string(),
        // decimal strings, not numbers: a double cannot hold the digits of an exact amount
        "decimal" | "money" => "string".to_string(),
        "text" | "rich_text" | "email" | "url" | "phone" | "time" | "date" | "duration" | "uuid" | "entity" | "object" => "string".to_string(),
        "enum" | "record" => v.get("name").and_then(|n| n.as_str()).map(pascal).unwrap_or_else(|| "unknown".into()),
        "set" | "list" => {
            let inner = ts_type(v.get("of").unwrap_or(&Value::Null));
            format!("Array<{inner}>")
        }
        "range" => {
            let inner = ts_type(v.get("of").unwrap_or(&Value::Null));
            format!("{{ start: {inner}; end: {inner} }}")
        }
        "upload" => "Blob".to_string(),
        "union" | "union_ref" => {
            let ents: Vec<String> = v
                .get("entities")
                .and_then(|e| e.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_str()).map(|x| format!("'{x}'")).collect())
                .unwrap_or_default();
            format!("{{ type: {}; id: string }}", if ents.is_empty() { "string".into() } else { ents.join(" | ") })
        }
        "snapshot" => "{ id: string; version: number }".to_string(),
        _ => "unknown".to_string(),
    };
    let base = if v.get("kind").and_then(|k| k.as_str()) == Some("object") && v.get("fields").is_some() { object(v) } else { base };
    if v.get("nullable").and_then(|n| n.as_bool()).unwrap_or(false) { format!("{base} | null") } else { base }
}

fn object(v: &Value) -> String {
    let Some(fields) = v.get("fields").and_then(|f| f.as_object()) else { return "{}".into() };
    let parts: Vec<String> = fields.iter().map(|(k, t)| format!("{k}: {}", ts_type(t))).collect();
    format!("{{ {} }}", parts.join("; "))
}

fn input(params: &Value) -> String {
    let Some(ps) = params.as_array() else { return "{}".into() };
    let parts: Vec<String> = ps
        .iter()
        .map(|p| {
            let name = p.get("name").and_then(|n| n.as_str()).unwrap_or("_");
            let opt = p.get("optional").and_then(|o| o.as_bool()).unwrap_or(false);
            let t = ts_type(p.get("ty").unwrap_or(&Value::Null));
            if opt { format!("{name}?: {t} | null") } else { format!("{name}: {t}") }
        })
        .collect();
    format!("{{ {} }}", parts.join("; "))
}

fn errors(es: &Value) -> String {
    let Some(arr) = es.as_array() else { return "AipErrorBody".into() };
    let mut parts: Vec<String> = arr
        .iter()
        .map(|e| {
            let code = e.get("code").and_then(|c| c.as_str()).unwrap_or("");
            match e.get("reason").and_then(|r| r.as_str()) {
                Some(r) => format!("{{ code: '{code}'; reason: '{r}' }}"),
                None => format!("{{ code: '{code}' }}"),
            }
        })
        .collect();
    parts.sort();
    parts.dedup();
    if parts.is_empty() { "never".into() } else { parts.join("\n  | ") }
}

pub fn generate(contract: &Value) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by `aip gen ts` from the AIP contract {} (core {}). Do not edit.",
        contract.get("protocol").and_then(|v| v.as_str()).unwrap_or(""),
        contract.get("core_ir").and_then(|v| v.as_str()).unwrap_or("")
    );
    let _ = writeln!(out, "/* eslint-disable */\n");
    if let Some(enums) = contract.get("enums").and_then(|e| e.as_object()) {
        for (name, vals) in enums {
            let lits: Vec<String> =
                vals.as_array().map(|a| a.iter().filter_map(|v| v.as_str()).map(|v| format!("'{v}'")).collect()).unwrap_or_default();
            let _ = writeln!(out, "export type {} = {};", pascal(name), lits.join(" | "));
        }
    }
    let _ = writeln!(out);
    if let Some(records) = contract.get("records").and_then(|e| e.as_object()) {
        for (name, fields) in records {
            let _ = writeln!(out, "export type {} = {};", pascal(name), input(fields));
        }
    }
    let _ = writeln!(out);
    let mut q_entries = Vec::new();
    let mut c_entries = Vec::new();
    for (kind, entries) in [("queries", &mut q_entries), ("commands", &mut c_entries)] {
        let Some(ops) = contract.get(kind).and_then(|q| q.as_object()) else { continue };
        for (name, op) in ops {
            let _ = writeln!(out, "export type {name}Input = {};", input(op.get("input").unwrap_or(&Value::Null)));
            let output = match op.get("output") {
                Some(Value::Null) | None => "null".to_string(),
                Some(o) => ts_type(o),
            };
            let _ = writeln!(out, "export type {name}Output = {output};");
            let _ = writeln!(out, "export type {name}Error =\n  | {};\n", errors(op.get("errors").unwrap_or(&Value::Null)));
            let key_required = op.get("idempotency").and_then(|i| i.as_str()) == Some("Idempotency-Key header required");
            let list = op.get("returns").and_then(|r| r.as_str()) == Some("list");
            entries.push((name.clone(), key_required, list));
        }
    }
    let mut sub_names = Vec::new();
    if let Some(subs) = contract.get("subscriptions").and_then(|q| q.as_object()) {
        for (name, op) in subs {
            let _ = writeln!(out, "export type {name}Input = {};", input(op.get("input").unwrap_or(&Value::Null)));
            let _ = writeln!(out, "export type {name}Output = {};", ts_type(op.get("output").unwrap_or(&Value::Null)));
            let _ = writeln!(out, "export type {name}Error =\n  | {};\n", errors(op.get("errors").unwrap_or(&Value::Null)));
            sub_names.push(name.clone());
        }
    }
    out.push_str(RUNTIME);
    if !sub_names.is_empty() {
        out.push_str(SUBSCRIBE_RUNTIME);
        let _ = writeln!(out, "export type Subscriptions = {{");
        for name in &sub_names {
            let _ = writeln!(out, "  {name}: {{ input: {name}Input; output: {name}Output; error: {name}Error }};");
        }
        let _ = writeln!(out, "}};\n");
    }
    let opts_ty = if sub_names.is_empty() { "ClientOptions" } else { "SubscribeClientOptions" };
    let _ = writeln!(out, "export function createClient(opts: {opts_ty}) {{\n  const call = makeCall(opts);\n  return {{\n    queries: {{");
    for (name, _, list) in &q_entries {
        if *list {
            let _ = writeln!(
                out,
                "      {name}: (input: {name}Input, page?: PageRequest) => call<{name}Output, {name}Error>('{name}', {{ ...input, ...(page ?? {{}}) }}),"
            );
        } else {
            let _ = writeln!(out, "      {name}: (input: {name}Input) => call<{name}Output, {name}Error>('{name}', input),");
        }
    }
    let _ = writeln!(out, "    }},\n    commands: {{");
    for (name, key, _) in &c_entries {
        if *key {
            let _ = writeln!(
                out,
                "      {name}: (input: {name}Input, o: {{ idempotencyKey: string }}) => call<{name}Output, {name}Error>('{name}', input, o.idempotencyKey),"
            );
        } else {
            let _ = writeln!(out, "      {name}: (input: {name}Input) => call<{name}Output, {name}Error>('{name}', input),");
        }
    }
    let _ = writeln!(out, "    }},");
    if !sub_names.is_empty() {
        let _ = writeln!(out, "    subscribe: makeSubscribe<Subscriptions>(opts),");
    }
    let _ = writeln!(out, "  }};\n}}");
    out
}

const RUNTIME: &str = r#"export interface AipErrorBody {
  code: string;
  intent: string;
  reason?: string;
  path?: string;
  message: string;
  retryable: boolean;
}

/** Thrown for every failed call; `body` is narrowed per intent by the generated error unions. */
export class AipError<E = { code: string }> extends Error {
  readonly body: AipErrorBody & E;
  readonly status: number;
  constructor(status: number, body: AipErrorBody & E) {
    super(`${body.code}${body.reason ? ` (${body.reason})` : ''}: ${body.message}`);
    this.status = status;
    this.body = body;
  }
}

export interface ClientOptions {
  baseUrl: string;
  /** Bearer token, or a function returning one (for refresh). */
  token?: string | (() => string | undefined | Promise<string | undefined>);
  fetch?: typeof fetch;
}

export interface PageRequest {
  cursor?: string | null;
  page?: number;
}

export interface Page {
  next_cursor?: string | null;
  has_more: boolean;
}

export interface Result<O> {
  data: O;
  page?: Page;
  items?: Array<{ index: number; ok: boolean; error?: AipErrorBody }>;
}

/** Replaces Blob values with part names and collects the files for multipart upload. */
function extractFiles(value: unknown, files: Map<string, Blob>): unknown {
  if (typeof Blob !== 'undefined' && value instanceof Blob) {
    const name = `file${files.size}`;
    files.set(name, value);
    return name;
  }
  if (Array.isArray(value)) return value.map((v) => extractFiles(v, files));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, extractFiles(v, files)]));
  }
  return value;
}

function makeCall(opts: ClientOptions) {
  const f = opts.fetch ?? fetch;
  return async function call<O, E>(intent: string, input: unknown, idempotencyKey?: string): Promise<Result<O>> {
    const headers: Record<string, string> = {};
    const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
    if (token) headers['authorization'] = `Bearer ${token}`;
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const files = new Map<string, Blob>();
    const payload = extractFiles(input, files);
    let body: BodyInit;
    if (files.size > 0) {
      const form = new FormData();
      form.append('input', JSON.stringify(payload));
      for (const [name, blob] of files) form.append(name, blob, (blob as File).name ?? name);
      body = form;
    } else {
      headers['content-type'] = 'application/json';
      body = JSON.stringify(payload);
    }
    const res = await f(`${opts.baseUrl}/aip/${intent}`, { method: 'POST', headers, body });
    const json = (await res.json()) as { data?: O; page?: Page; items?: Result<O>['items']; error?: AipErrorBody };
    if (!res.ok || json.error) throw new AipError<E>(res.status, json.error as AipErrorBody & E);
    return { data: json.data as O, page: json.page, items: json.items };
  };
}

"#;

/// Only in a client whose program declares a `subscribe`: one WebSocket per subscription. There is no automatic
/// reconnect: a dropped connection is reported through `onError` and the caller subscribes again, which starts
/// with a fresh snapshot, so nothing that changed meanwhile is missed.
const SUBSCRIBE_RUNTIME: &str = r#"export interface SubscribeClientOptions extends ClientOptions {
  /** The WebSocket constructor; defaults to the global one (browsers, Node 22+). */
  webSocket?: typeof WebSocket;
}

export interface Subscription {
  /** Ends the subscription and closes its connection. Safe to call twice. */
  close(): void;
}

/** What the server says when it ends a subscription, or the connection drops (`AIP.UNAVAILABLE`). */
export type SubscriptionFailure<E> = AipErrorBody & E;

function makeSubscribe<M extends Record<string, { input: unknown; output: unknown; error: unknown }>>(opts: SubscribeClientOptions) {
  return function subscribe<N extends keyof M & string>(
    name: N,
    input: M[N]['input'],
    onRows: (rows: M[N]['output'], kind: 'snapshot' | 'changed') => void,
    onError?: (error: SubscriptionFailure<M[N]['error']>) => void,
  ): Subscription {
    const WS = opts.webSocket ?? WebSocket;
    const id = Math.random().toString(36).slice(2);
    let done = false;
    const ws = new WS(`${opts.baseUrl.replace(/^http/, 'ws')}/aip/subscribe`);
    const fail = (body: AipErrorBody & { id?: string }) => {
      if (done) return;
      done = true;
      ws.close();
      onError?.(body as SubscriptionFailure<M[N]['error']>);
    };
    ws.onopen = async () => {
      // the token goes in the first message, not in the URL: URLs end up in logs and browsers cannot set headers on a WebSocket
      const token = typeof opts.token === 'function' ? await opts.token() : opts.token;
      ws.send(JSON.stringify({ type: 'auth', ...(token ? { token } : {}) }));
      ws.send(JSON.stringify({ type: 'subscribe', id, name, input }));
    };
    ws.onmessage = (ev) => {
      const msg = JSON.parse(String(ev.data)) as { type: string; id?: string; rows?: M[N]['output'] } & AipErrorBody;
      if (msg.id !== undefined && msg.id !== id) return;
      if (msg.type === 'snapshot' || msg.type === 'changed') {
        if (!done) onRows(msg.rows as M[N]['output'], msg.type);
      } else if (msg.type === 'error') {
        fail(msg);
      }
    };
    ws.onerror = () => fail({ code: 'AIP.UNAVAILABLE', intent: name, message: 'the connection failed', retryable: true });
    ws.onclose = () => fail({ code: 'AIP.UNAVAILABLE', intent: name, message: 'the connection was closed', retryable: true });
    return {
      close() {
        if (done) return;
        done = true;
        ws.close();
      },
    };
  };
}

"#;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn decimal_and_money_are_strings_ints_are_numbers() {
        assert_eq!(ts_type(&json!({"kind": "decimal"})), "string");
        assert_eq!(ts_type(&json!({"kind": "money", "currency": "KRW", "nullable": true})), "string | null");
        assert_eq!(ts_type(&json!({"kind": "int"})), "number");
    }
}
