use spike_v1_fixture::{load_str, Form};
use spike_v2_read::sqlgen;

#[test]
fn non_primary_typed_id_field_has_a_postgres_column() {
    let source = r#"
resource Member { fields { id: Id } }
actor Member
resource SalesOrder { fields { id: Id; successor: SalesOrder.Id? } }
"#;
    let facts = load_str(source, Form::A).unwrap_or_else(|errors| panic!("V1: {errors:?}")).execution;
    assert_eq!(facts["resources"]["SalesOrder"]["fields"]["successor"]["ty"], "Id<SalesOrder>?");
    let ddl = sqlgen::create_ddl_in("aip_typed_id_gap", &facts).expect("an accepted Id<T> field needs executable DDL");
    assert!(ddl.iter().any(|statement| statement.contains("successor bigint")), "{ddl:?}");
}

#[test]
fn mutually_typed_ids_have_no_foreign_key_dependency() {
    let source = r#"
resource First { fields { id: Id; second: Second.Id? } }
resource Second { fields { id: Id; first: First.Id? } }
actor First
"#;
    let facts = load_str(source, Form::A).unwrap_or_else(|errors| panic!("V1: {errors:?}")).execution;
    let ddl = sqlgen::create_ddl_in("aip_typed_id_cycle", &facts).expect("plain Id<T> columns do not impose table order");
    assert!(
        ddl.iter().any(|statement| statement
            .contains("CREATE TABLE aip_typed_id_cycle.first (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, second bigint)")),
        "{ddl:?}"
    );
    assert!(
        ddl.iter().any(|statement| statement
            .contains("CREATE TABLE aip_typed_id_cycle.second (first bigint, id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)")),
        "{ddl:?}"
    );
    assert!(!ddl.iter().any(|statement| statement.contains("REFERENCES")), "{ddl:?}");
}

#[test]
fn ref_field_keeps_its_existing_foreign_key() {
    let source = r#"
resource Member { fields { id: Id } }
actor Member
resource Child { fields { id: Id; parent: Member } }
"#;
    let facts = load_str(source, Form::A).unwrap().execution;
    let ddl = sqlgen::create_ddl_in("aip_typed_id_fk", &facts).unwrap();
    assert!(ddl.iter().any(|statement| statement.contains("parent_id bigint REFERENCES aip_typed_id_fk.member(id) NOT NULL")), "{ddl:?}");
}
