// Contract → TypeScript client. Generated from the contract (not the DSL) so
// any consumer that can read /aip/describe could produce the same client.

import type { CType, Contract } from './contract.ts';

function ts(t: CType, indent = ''): string {
  if (typeof t === 'string') return { UUID: 'string', String: 'string', Int: 'number', Bool: 'boolean' }[t];
  if ('enum' in t) return t.enum;
  if ('nullable' in t) return `${ts(t.nullable, indent)} | null`;
  if ('list' in t) {
    const inner = ts(t.list, indent);
    return inner.includes('|') ? `Array<${inner}>` : `${inner}[]`;
  }
  const inner = indent + '  ';
  const fields = Object.entries(t.object).map(([k, v]) => `${inner}${k}: ${ts(v, inner)};`);
  return fields.length ? `{\n${fields.join('\n')}\n${indent}}` : '{}';
}

function errorUnion(errors: { code: string; reasons?: string[] }[]): string {
  return errors
    .map((e) => (e.reasons ? `{ code: '${e.code}'; reason: ${e.reasons.map((r) => `'${r}'`).join(' | ')} }` : `{ code: '${e.code}' }`))
    .join('\n  | ');
}

export function generateClient(c: Contract): string {
  const out: string[] = [];
  out.push('// Generated by `aip gen-client`. Do not edit.', `// AIP contract version ${c.aip}`, '');
  for (const [name, values] of Object.entries(c.enums)) out.push(`export type ${name} = ${values.map((v) => `'${v}'`).join(' | ')};`);
  out.push('');
  for (const [name, op] of Object.entries(c.queries)) {
    out.push(`export type ${name}Input = ${ts({ object: op.input })};`);
    out.push(`export type ${name}Output = ${ts(op.output as CType)};`);
    out.push(`export type ${name}Error =\n  | ${errorUnion(op.errors)};`, '');
  }
  for (const [name, op] of Object.entries(c.commands)) {
    out.push(`export type ${name}Input = ${ts({ object: op.input })};`);
    out.push(`export type ${name}Output = ${op.output ? ts(op.output as CType) : 'null'};`);
    out.push(`export type ${name}Error =\n  | ${errorUnion(op.errors)};`, '');
  }
  out.push(`export interface AipErrorBody {
  code: string;
  operation: string;
  reason?: string;
  path?: string;
  message: string;
  retryable: boolean;
}

export class AipClientError<E = { code: string }> extends Error {
  body: AipErrorBody & E;
  status: number;
  constructor(status: number, body: AipErrorBody & E) {
    super(\`\${body.code}\${body.reason ? ' (' + body.reason + ')' : ''}: \${body.message}\`);
    this.status = status;
    this.body = body;
  }
}

export interface ClientOptions {
  baseUrl: string;
  // DEV ONLY: sent as x-aip-actor.
  actor?: string;
  fetch?: typeof fetch;
}

export function createClient(opts: ClientOptions) {
  const f = opts.fetch ?? fetch;
  async function call<O>(kind: 'query' | 'command', name: string, input: unknown, idempotencyKey?: string): Promise<O> {
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    if (opts.actor) headers['x-aip-actor'] = opts.actor;
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const res = await f(\`\${opts.baseUrl}/aip/\${kind}/\${name}\`, { method: 'POST', headers, body: JSON.stringify(input) });
    const body = (await res.json()) as { data?: O; error?: AipErrorBody };
    if (!res.ok || body.error) throw new AipClientError(res.status, body.error!);
    return body.data as O;
  }
  return {
    queries: {`);
  for (const name of Object.keys(c.queries)) {
    out.push(`      ${name}: (input: ${name}Input) => call<${name}Output>('query', '${name}', input),`);
  }
  out.push('    },', '    commands: {');
  for (const [name, op] of Object.entries(c.commands)) {
    if (op.idempotent) out.push(`      ${name}: (input: ${name}Input, opts: { idempotencyKey: string }) => call<${name}Output>('command', '${name}', input, opts.idempotencyKey),`);
    else out.push(`      ${name}: (input: ${name}Input) => call<${name}Output>('command', '${name}', input),`);
  }
  out.push('    },', '  };', '}', '');
  return out.join('\n');
}
